services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - MYSQL_HOST=mysql 
      - MYSQL_USER=root 
      - MYSQL_PASSWORD=password 
      - MYSQL_DATABASE=ecommerce
      - REDIS_HOST=redis
    volumes:
      - .:/app
  
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password 
      - MYSQL_DATABASE=ecommerce
      - FLASK_SECRET_KEY=f4406b276e683d6157f623503bc6f2db5ebc484ac99f64b5802653be9681c4c0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
  
volumes:
  mysql_data:
